### ISSUE TITLE
Display error in Gamelog

### ISSUE THREAD

**Issue by tobiasff3200** [TobiasMie/Schiffeversenken#23]
Manchmal ist die Darstellung des GameLog fehlerhaft.
![screenshot](https://user-images.githubusercontent.com/19272532/49653726-1c03f700-fa36-11e8-92ec-1473344e0960.png)
Auf einem anderen Gerät war es nur, wenn ein Schiff zerstört wurde.

**Comment by CrazyMan2000** [comment]
Also ich konnte den Fehler nicht wirklich nachstellen aber versuch jz nochmal. Sollte klappen glaub ich.
