### ISSUE TITLE
Overlay doesnt block inputs

### ISSUE THREAD

**Issue by CrazyMan2000** [TobiasMie/Schiffeversenken#25]

**Comment by CrazyMan2000** [comment]
Im Overlay kann man die Schiffe bewegen und Tasten dücken. 
Das müsste geblockt werden, ggf. mit einer Variable oder anders.

**Comment by CrazyMan2000** [comment]
wenn du das mit ner variable machen willst sag bescheid dann baue ich das ein

**Comment by tobiasff3200** [comment]
Ja ich denke mit einer Variable wäre es am einfachsten. Wir könnten einfach waiting for Server nehmen, was es ja in gewisser weise tut oder sollten wir nicht besser eine neue nehmen?

**Comment by CrazyMan2000** [comment]
ja gut Idee. Dann initialisieren wir die einfach mit true und sobald das spiel startet müssen wir sie dann auf false setzten.

**Comment by CrazyMan2000** [comment]
Ich glaube das einfachste wäre wenn man das in closeOverlay wieder "aktiviert" oder? 
Denn das wird ja bei beiden aufjedenfall ausgeführt oder?
Kann das grad nicht testen weil der Server iwie down ist.

**Comment by tobiasff3200** [comment]
Ja so habe ich es jetzt gemacht
