### ISSUE TITLE
Overlay bug

### ISSUE THREAD

**Issue by CrazyMan2000** [TobiasMie/Schiffeversenken#26]
Wenn Zwei Clients die Seite kurz hintereinander laden verwechselt der Server den Sender und den Empfänger des Token.

Bsp.: Client A und Client B rufen die Seite auf. Client A drückt auf "create Game" aber es ändert sich nicht. Bei Client B jedoch ändert sich das Overlay als hätte man auf "create Game" geclicket.

**Comment by tobiasff3200** [comment]
Müsste gefixt sein. Falls der Fehler wieder auftritt sollte der Issue wiedereröffnet werden.

**Comment by CrazyMan2000** [comment]
Ich weiß nicht genau wo der Fehler ist aber es passieren immer andere Dinge.
Manchmal klappt alles ohne probleme, 
manchmal wird bei create Game das Overlay beim gegner geändert,
manchmal wird nachdem man einen Code eingegeben hat beim Gegner das Overlay geschlossen aber bei einem selber nicht.
Wir müssen mal versuchen den Fehler nachzustellen und dann überlegen woran es liegt
