### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by tobiasff3200** [TobiasMie/Schiffeversenken#30]
Wir sollten uns einigen, auf welcher Sprache das Spiel sein soll. Der Inhalt ist zur Zeit auf Englisch, was ich auch so lassen würde, aber der Titel ist noch auf Deutsch.
Laut [Wikipedia](https://en.wikipedia.org/wiki/Battleship_(game)) ist der englische Name "Battleship".
Sollen wir das übernehmen?

**Comment by CrazyMan2000** [comment]
ja

**Comment by tobiasff3200** [comment]
Ich hoffe ich habe nichts vergessen
